"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter,Quicksand } from 'next/font/google'
import { GoogleOAuthProvider } from '@react-oauth/google'
const inter = Inter({ subsets: ['latin'] })
const quicksand = Quicksand({ subsets: ['latin'] })



// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <div className={inter.className} >
      
      <body > <GoogleOAuthProvider clientId='270812207045-774f9vvqijam6stisa5e6uld8msmn48t.apps.googleusercontent.com'>  {children} </GoogleOAuthProvider></body>
      </div>
      
    
    </html>
  )
}
